services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3034:3000"
    depends_on:
      - postgres
    environment:
      - PLACEHOLDER=YES
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - uploads:/usr/src/app/public/uploads
    command: npm run dev

  postgres:
    image: postgres:17
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PLACEHOLDER: "YES"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
      - .sql_data:/docker-entrypoint-initdb.d/

volumes:
  postgres_db_data:
  uploads:
