# Stage 1: Development Stage
FROM node:21-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port Next.js runs on
EXPOSE 3000

# Set environment variables to enable hot-reloading
ENV CHOKIDAR_USEPOLLING=true

# Start the Next.js app in development mode
CMD ["npm", "run", "dev"]
