services:
  uppy:
    build: .
    restart: unless-stopped
    ports:
      - "3034:3000"
    env_file:
      - .env
    image: "reg.nheek.com/nheek/uppy:latest"
    volumes:
      - uploads:/usr/src/app/public/uploads

volumes:
  uploads:
